// What you need is to get the k-th minimum value of data

// Process is initialized with three parameters
// 0 <= N <= 10^7
// 0 <  M <= 10^4
// 0 < q0 <  2^31

// data sequence 'x' is generated from the quantum data sequence 'q'

// you are given q0 value - the next items are generated using this formula
// q_i = (q_i-1 * 7^5) mod (2^31 - 1)

// the data you need to analyze is calculated from quantum data
// x_i = (q_i mod M) - M // 2

// number of values generated by this process N
// you should calculate the k-th minimum value of this array.

// You are not allowed to use any built-in sorting.

// Input format
// N M q0 k             where 1 <= k <= N

// Output format
// k-th minimum element

#include <iostream>
#include <cmath>
#include <vector>
#include <algorithm>

long long quantum_a()
{
    return std::pow(7, 5);
}

long long quantum_m()
{
    return std::pow(2, 31) - 1;
}

static void insertion_sort(std::vector<long long> &x, long long lo, long long hi)
{
    for (long long i = lo + 1; i <= hi; i++)
    {
        long long key = x[i];
        long long j = i - 1;
        while (j >= lo && x[j] > key)
        {
            x[j + 1] = x[j];
            j--;
        }
        x[j + 1] = key;
    }
}

long long median_of_medians(std::vector<long long> &x, long long left, long long right)
{
    long long size = right - left + 1;

    if (size <= 5)
    {
        insertion_sort(x, left, right);
        return x[left + (size - 1) / 2]; // lower-middle median
    }

    long long median_count = 0;
    for (long long gs = left; gs <= right; gs += 5)
    {
        long long ge = std::min(gs + 4, right);
        insertion_sort(x, gs, ge);
        long long gsize = ge - gs + 1;
        long long gmedian_idx = gs + (gsize - 1) / 2; // lower-middle
        std::swap(x[left + median_count], x[gmedian_idx]);
        median_count++;
    }

    return median_of_medians(x, left, left + median_count - 1);
}

long long quickselect(std::vector<long long> &x, long long left, long long right, long long k_index)
{
    while (true)
    {
        if (left == right)
            return x[left];

        long long pivot = median_of_medians(x, left, right);

        long long lt = left, i = left, gt = right;
        while (i <= gt)
        {
            if (x[i] < pivot)
            {
                std::swap(x[lt], x[i]);
                lt++;
                i++;
            }
            else if (x[i] > pivot)
            {
                std::swap(x[i], x[gt]);
                gt--;
            }
            else
            {
                i++;
            }
        }
        // [left..lt-1] < pivot,
        // [lt..gt] == pivot,
        // [gt+1..right] > pivot

        if (k_index < lt)
            right = lt - 1;
        else if (k_index > gt)
            left = gt + 1;
        else
            return pivot;
    }
}

long long kth_smallest(std::vector<long long> x, long long k)
{
    if (x.empty())
        return -1;
    return quickselect(x, 0, (long long)x.size() - 1, k - 1);
}

long long analyze_trimpazation(long long n, long long m, long long q0, long long k)
{
    long long m_div2 = m / 2;
    long long q = q0;

    // generating x data:
    std::vector<long long> x;
    x.reserve(n);

    for (long long i = 0; i < n; i++)
    {
        long long x_i = (q % m) - m_div2;
        x.push_back(x_i);
        q = (q * quantum_a()) % quantum_m();
    }

    return kth_smallest(x, k);
}

int main()
{
    long long N, M, q0, k;
    std::cin >> N >> M >> q0 >> k;
    std::cout << analyze_trimpazation(N, M, q0, k) << std::endl;

    return 0;
}
